 GET http://localhost:5000/api/news HTTP/1.1
 Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmbEBnbWFpLmNvbSIsInVzZXJuYW1lIjoicWIyMmJlIiwiaWF0IjoxNzMyMDMyMzIzLCJleHAiOjE3MzIwNzU1MjN9.N9T_2l7ZNUf_5XJgDjsqrveZtjqQgvF-mHf7iLbs32I