POST http://localhost:5000/api/email/membership-request
Content-Type: application/json

{
  "firstName": "возьмите меня пожайлуста в профсоюз ",
  "lastName": "очень",
  "phone": "+1234567890",
  "email": "iv@example.com"
}
